FROM node:20-alpine AS base
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
ARG NEXT_PUBLIC_API_URL=https://bookingnail.basic.overpowers.agency
ARG NEXT_PUBLIC_GOOGLE_CLIENT_ID=
ARG NEXT_PUBLIC_APP_EDITION=basic
ARG NEXT_PUBLIC_ENABLE_CHATBOT=false
ARG NEXT_PUBLIC_ENABLE_SOCIAL_BUBBLES=true
ARG NEXT_PUBLIC_SHOP_LANGUAGE=en
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_GOOGLE_CLIENT_ID=$NEXT_PUBLIC_GOOGLE_CLIENT_ID
ENV NEXT_PUBLIC_APP_EDITION=$NEXT_PUBLIC_APP_EDITION
ENV NEXT_PUBLIC_ENABLE_CHATBOT=$NEXT_PUBLIC_ENABLE_CHATBOT
ENV NEXT_PUBLIC_ENABLE_SOCIAL_BUBBLES=$NEXT_PUBLIC_ENABLE_SOCIAL_BUBBLES
ENV NEXT_PUBLIC_SHOP_LANGUAGE=$NEXT_PUBLIC_SHOP_LANGUAGE
RUN npm run build

FROM node:20-alpine
WORKDIR /app
ARG NEXT_PUBLIC_API_URL=https://bookingnail.basic.overpowers.agency
ARG NEXT_PUBLIC_GOOGLE_CLIENT_ID=
ARG NEXT_PUBLIC_APP_EDITION=basic
ARG NEXT_PUBLIC_ENABLE_CHATBOT=false
ARG NEXT_PUBLIC_ENABLE_SOCIAL_BUBBLES=true
ARG NEXT_PUBLIC_SHOP_LANGUAGE=en
ENV NODE_ENV=production
ENV PORT=3000
ENV HOSTNAME=0.0.0.0
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_GOOGLE_CLIENT_ID=$NEXT_PUBLIC_GOOGLE_CLIENT_ID
ENV NEXT_PUBLIC_APP_EDITION=$NEXT_PUBLIC_APP_EDITION
ENV NEXT_PUBLIC_ENABLE_CHATBOT=$NEXT_PUBLIC_ENABLE_CHATBOT
ENV NEXT_PUBLIC_ENABLE_SOCIAL_BUBBLES=$NEXT_PUBLIC_ENABLE_SOCIAL_BUBBLES
ENV NEXT_PUBLIC_SHOP_LANGUAGE=$NEXT_PUBLIC_SHOP_LANGUAGE
COPY --from=base /app/.next/standalone ./
COPY --from=base /app/.next/static ./.next/static
COPY --from=base /app/public ./public
EXPOSE 3000
CMD ["node", "server.js"]
